### ISSUE TITLE
calendario controllo inserimento

### ISSUE THREAD

**Issue by lupaelma** [lupaelma/realteam#111]
- calendario non risponde a inserimento con date vuote
- c'e' un errore ma non viene mostrato alcun messaggio
- bisogna verificare che i campi data e ora siano settati e anche from <= to

Il controllo viene fatto da RtUtil.validateStateCalendarDTO(StateCalendarDTO) che viene chiamata sia da mobile app che da calendario app. Vedi esempio DTO in dataloader app.

**Comment by samirlegdah** [comment]
fatto
