### ISSUE TITLE
Navbar scrolla... dovrebbe essere fisso come header

### ISSUE THREAD

**Issue by lupaelma** [lupaelma/realteam#38]

**Comment by samirlegdah** [comment]
Ciao Luigi, sto guardando ora realteam, ma sia su pc che sul mio smarphone non da problemi la navbar riguardo allo scroll.. è stato gia risolto per caso ?

**Comment by lupaelma** [comment]
Prova a creare semplicemente un altra div con data-role=header...

**Comment by samirlegdah** [comment]
non ho piu saputo se hai ancora problemi con la navbar

**Comment by lupaelma** [comment]
Non lo so perche` aspettavo la tua PR... ora che posso fare il merge controllo. Comunque penso che dovremmo togliere il navbar e usare un drop down menu accessibile da header a destra con le opzioni del navbar + esci. Insieme a swipe direi che va bene. Creo una issue cosi' provi come viene...

**Comment by samirlegdah** [comment]
fammi sapere, comunque tenere il navbar è utile secondo me, rendere raggiungibile le funzionalita principali in modo semplice e veloce, il drop down si va fatto, ma non potremmo tenerlo piu per le impostazioni utente (future se ci saranno) + esci ?

**Comment by lupaelma** [comment]
magari fai una prova...

**Comment by samirlegdah** [comment]
va bene
