### ISSUE TITLE
calendario app

### ISSUE THREAD

**Issue by lupaelma** [lupaelma/realteam#39]
- use standard header
- rimuovere ID column

**Comment by eliasuardi** [comment]
Ehi pa! Problemino con il jsgrid.
Le operazioni di loadData, insertItem e deleteItem funzionano tranne l'updateItem di un record appena inserito. Non si memorizza l'id giusto del record (si tiene memorizzato l'id dell'inserimento che è 0 siccome non si tocca).
Come si potrebbe fare per aggiornare l'id del record appena inserito?
Domani chiamo casa per chiarire meglio.

**Comment by lupaelma** [comment]
l'update non deve cambiare l'id... altrimenti non si chiamerebbe update... sarebbe insert...

**Comment by eliasuardi** [comment]
Ma serve per dire modifica la riga con id del item.

**Comment by lupaelma** [comment]
Sta venendo bene! Altre cose da fare:

- i titoli delle colonne da catalogo e in italiano
- ordine delle colonne: stato pianificato, giorno e ora di inizio, giorno e ora di fine
- lo stato pianificato deve essere una tendina calcolata dalla configurazione... vedi stateful calendario
- bottone esci inline (non 100% width)
