### ISSUE TITLE
Caserma deve calcolare i turni delle squadre con una formula

### ISSUE THREAD

**Issue by lupaelma** [lupaelma/realteam#45]
Si parte da squadra A "inizio":"26/12/2015 08:00", "fine":"02/01/2016 08:00" e si procede sequenzialmente con le settimane successive assegnate a B, C, D, etc... per un giorno qualunque e` facile calcolare quali squadre sono di turno. Il calcolo viene utilizzato per visualizzare chi e' di turno o no in caserma. Aggiungiamo un metodo RtConfig.getTurni() che ritorna un oggetto
{
  "A": true,
  "B": false,
  "C": true,
  "D": false
}
in base all'istante in cui viene richiesto e alla formula di calcolo. Quando hai questo oggetto puoi facilmente controllare se un utente e' di turno tramite la sua squadra di appartenenza.

**Comment by lupaelma** [comment]
Ignora questo commento...

    "turni":
    {
        "A":
        [
            {"inizio":"26/12/2015 08:00", "fine":"02/01/2016 08:00"},
            {"inizio":"23/01/2016 08:00", "fine":"30/01/2016 08:00"}
        ],
        "B":
        [
            {"inizio":"02/01/2016 08:00", "fine":"09/01/2016 08:00"},
            {"inizio":"30/01/2016 08:00", "fine":"06/02/2016 08:00"}
        ],
        "C":
        [
            {"inizio":"09/01/2016 08:00", "fine":"16/01/2016 08:00"},
            {"inizio":"06/02/2016 08:00", "fine":"13/02/2016 08:00"}
        ],
        "D":
        [
            {"inizio":"16/01/2016 08:00", "fine":"23/01/2016 08:00"},
            {"inizio":"13/02/2016 08:00", "fine":"20/02/2016 08:00"}
        ]
    }

**Comment by samirlegdah** [comment]
{
"A": true,
"B": false,
"C": true,
"D": false
}

 sono di turno sia A che C, bisogna specificare che una delle due squadre è quella di beckup ?

**Comment by lupaelma** [comment]
la formula puo` anche indicare che ` di backup... e l'oggetto puo` contenere un flag "backup":true

**Comment by samirlegdah** [comment]
va bene, sisi l'ho capito, è quasi finita, sto sistemando ancora due cose...se può serivre , la funzione può indica anche tutti i turni prossimi o passati delle altre squadre (ovviamente riferito al periodo di tempo in qui si richiamata la funziona) ...
es
{   A: {
            turno : true,
            inizio : data e ora,
            fine   : data e ora,
            backup: false
          },
    B: {
            turno : false,
            inizio : data e ora,
            fine   : data e ora,
            backup: true
          },
    ........
altrimenti faccio solo restituire un oggetto del tipo di quello che mi hai mostrato in alto

**Comment by lupaelma** [comment]
Mi sembra che B non fa il backup di A... Le date di inizio/fine non servono... L'oggetto ritornato contiene i turni in un istante preciso, non sul periodo. Fai cosi':

{
  "A": {"turno":true, "backup":false},
  "B": {"turno":false, "backup":false},
  "C": {"turno":true, "backup":true},
  "D": {"turno":false, "backup":false}
}

cioe' la squadra di backup e' anche di turno...

**Comment by samirlegdah** [comment]
fatto

**Comment by lupaelma** [comment]
Bisogna generalizzare il codice di aggregazione in modo che sia indipendente dagli id degli stati e quindi possa funzionare per qualunque configurazione. Comincia a far vedere un conteggio di tutti gli stati trovati, per esempio:

| Stato  | Totale |
| ------------- | ------------- |
| DiTurno  | 10 |
| Disponibile  | 12  |
| Assente  | 11  |
