### ISSUE TITLE
preparare ambiente di prova locale e su mondoserver

### ISSUE THREAD

**Issue by lupaelma** [lupaelma/realteam#58]
- creare nuovo tenant vdfprova = vdftreviglio
- creare tabella SQL vdfprova_calendario
- creare database realteam su mondoserver
- creare nuovo war file realteam-prova
- creare nuova applicazione tomcat
- deploy realteam-prova su tomcat

**Comment by eliasuardi** [comment]
-modifica di RtUtil per prendere l'applicazione dall'url
