### ISSUE TITLE
configurazione dell'ordine dei bottoni nella stateful app

### ISSUE THREAD

**Issue by lupaelma** [lupaelma/realteam#66]
I bottoni della stateful corrispondono agli eventi della configurazione JSON. Possiamo aggiungere un campo displayOrder che permette alla UI di visualizzare i bottoni nell'ordine desiderato.

**Comment by samirlegdah** [comment]
l'ordine di questi bottoni come deve essere deciso ?

**Comment by lupaelma** [comment]
Bottoni ordinati per transition ID specificato nel JSON
