### ISSUE TITLE
Sostituzione

### ISSUE THREAD

**Issue by lupaelma** [lupaelma/realteam#95]
Prendere spunto dalla pagina mobile Calendario... praticamente devi copiare calendario.js in sostituzione.js e fare le modifiche necessarie.
1. Aggiungere l'operazione Sostituzione al menu
2. Campi pagina sostituzione: utente sostituito, utente sostituente, da giorno-ora, a giorno-ora
3. Bottoni: aggiungi, ignora
4. Creare record nel calendario per utente sostituito con nota "Sostituzione utente sostituente => utente sostituito"
5. Creare record nel calendario per utente sostituente con nota "Sostituzione utente sostituente => utente sostituito"

**Comment by samirlegdah** [comment]
la visualizzazione della sostituzione fatta , verrà mostrata in "calendario" o sempre li in "sostituzione" ??

**Comment by lupaelma** [comment]
La pagina Sostituzione non ha il bottone aggiungi sopra... va direttamente in modalita' inserimento con un solo bottone Aggiungi sotto... quando l'inserimento e' completato puoi andare in calendario che fa vedere il record inserito...

**Comment by samirlegdah** [comment]
un pop-up che avverte delle sostituzione avvenuta ?

**Comment by lupaelma** [comment]
va bene

**Comment by lupaelma** [comment]
Buon lavoro sulla sostituzione. Ora aggiorna il fork. Poi ci sono un paio di miglioramenti:

Sotto il primo selettore di utente servono due selettori di stato (come RtApp.calendario.renderAddStateSelector che puoi spostare in RtApp)... il primo con titolo Stato *utente sostituito* per esempio 'Stato Testa' ... il secondo con titolo Stato *utente sostituente* ... questi selettori permettono di scegliere gli stati da salvare nel calendario... saranno sempre AssentePianificato e DisponibilePianificato ma non possiamo indovinare... i valori scelti vanno messi nello stateCalendarDTO prima di salvare nel calendario... vedi TODO in sostituzione.js

Per il popup usa RtAppBase.popup senza bottoni con messaggio 'Sostituzione avvenuta. Vai al Calendario. Dopo aver cliccato ovunque il popup va via e l'utente si trova al calendario.

**Comment by eliasuardi** [comment]
ehi sam! non fare nulla! cambiato idea.

**Comment by lupaelma** [comment]
Puoi continuare su sostituzione e farla diventare come calendario:

1) Quando apri la pagina vedi il bottone Aggiungi e la lista delle sostituzioni dell'utente collegato, con bottone X di rimozione... ogni elemento della lista deve far vedere informazione combinata dai due record del calendario che definiscono la sostituzione

2) Se utente rimuove una sostituzione devi rimuovere i due record del calendario che definiscono la sostituzione

3) se utente aggiunge funzione come ora ma dopo inserimento stai su sostituzione e fai vedere lista aggiornata
